[rospy.client][INFO] 2017-06-09 19:29:05,548: init_node, name[/marker_control_5057_1497061745501], pid[5057]
[xmlrpc][INFO] 2017-06-09 19:29:05,549: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-09 19:29:05,553: Started XML-RPC server [http://ip-172-31-19-100:59922/]
[rospy.init][INFO] 2017-06-09 19:29:05,553: ROS Slave URI: [http://ip-172-31-19-100:59922/]
[rospy.impl.masterslave][INFO] 2017-06-09 19:29:05,557: _ready: http://ip-172-31-19-100:59922/
[rospy.registration][INFO] 2017-06-09 19:29:05,564: Registering with master node http://localhost:44697
[xmlrpc][INFO] 2017-06-09 19:29:05,564: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2017-06-09 19:29:05,660: registered with master
[rospy.rosout][INFO] 2017-06-09 19:29:05,664: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-09 19:29:05,673: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-09 19:29:05,677: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-09 19:29:05,955: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-09 19:29:05,966: topic[/control_markers/update] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-09 19:29:05,982: topic[/attached_collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-09 19:29:05,986: topic[/collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-09 19:29:06,368: topic[/control_markers/update_full] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-09 19:29:24,801: topic[/joint_trajectory] adding connection to [http://ip-172-31-19-100:39590/], count 0
[rospy.internal][INFO] 2017-06-09 19:29:24,809: topic[/motion_planning_goal] adding connection to [/move_arm_5543_1497061764408], count 0
[rospy.internal][INFO] 2017-06-09 19:29:26,363: topic[/visualization_marker_array] adding connection to [/rosbridge_websocket], count 0
[rospy.internal][INFO] 2017-06-09 19:29:26,485: topic[/control_markers/feedback] adding connection to [http://ip-172-31-19-100:49922/], count 0
[rospy.internal][ERROR] 2017-06-09 19:30:37,406: Unable to initiate TCP/IP socket to ip-172-31-19-100:45609 (http://ip-172-31-19-100:39590/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rosout][WARNING] 2017-06-09 19:30:38,144: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2017-06-09 19:30:38,148: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][WARNING] 2017-06-09 19:30:38,584: Unknown error initiating TCP/IP socket to ip-172-31-19-100:45609 (http://ip-172-31-19-100:39590/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-09 19:30:38,588: topic[/joint_trajectory] removing connection to http://ip-172-31-19-100:39590/
