[rospy.client][INFO] 2017-06-10 01:44:18,431: init_node, name[/marker_control_31589_1497084258390], pid[31589]
[xmlrpc][INFO] 2017-06-10 01:44:18,431: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-10 01:44:18,436: Started XML-RPC server [http://ip-172-31-19-100:41827/]
[rospy.init][INFO] 2017-06-10 01:44:18,436: ROS Slave URI: [http://ip-172-31-19-100:41827/]
[rospy.impl.masterslave][INFO] 2017-06-10 01:44:18,440: _ready: http://ip-172-31-19-100:41827/
[xmlrpc][INFO] 2017-06-10 01:44:18,448: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-06-10 01:44:18,448: Registering with master node http://localhost:42299
[rospy.init][INFO] 2017-06-10 01:44:18,544: registered with master
[rospy.rosout][INFO] 2017-06-10 01:44:18,548: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-10 01:44:18,557: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-10 01:44:18,561: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-10 01:44:18,788: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-10 01:44:18,812: topic[/attached_collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-10 01:44:18,816: topic[/collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-10 01:44:18,840: topic[/control_markers/update] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-10 01:44:19,342: topic[/control_markers/update_full] adding connection to [/interactive_marker_proxy], count 0
[rospy.internal][INFO] 2017-06-10 01:44:20,417: topic[/visualization_marker_array] adding connection to [/rosbridge_websocket], count 0
[rospy.internal][INFO] 2017-06-10 01:44:20,472: topic[/control_markers/feedback] adding connection to [http://ip-172-31-19-100:45200/], count 0
[rospy.internal][INFO] 2017-06-10 01:44:29,292: topic[/joint_trajectory] adding connection to [http://ip-172-31-19-100:38323/], count 0
[rospy.internal][INFO] 2017-06-10 01:44:29,297: topic[/motion_planning_goal] adding connection to [/move_arm_32388_1497084268904], count 0
[rospy.internal][ERROR] 2017-06-10 01:45:59,481: Unable to initiate TCP/IP socket to ip-172-31-19-100:54066 (http://ip-172-31-19-100:38323/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2017-06-10 01:46:00,483: Unknown error initiating TCP/IP socket to ip-172-31-19-100:54066 (http://ip-172-31-19-100:38323/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-06-10 01:46:00,487: topic[/joint_trajectory] removing connection to http://ip-172-31-19-100:38323/
[rospy.internal][INFO] 2017-06-10 01:54:59,868: topic[/joint_trajectory] adding connection to [http://ip-172-31-19-100:40574/], count 0
[rospy.internal][INFO] 2017-06-10 01:54:59,872: topic[/motion_planning_goal] adding connection to [/move_arm_11047_1497084899485], count 1
[rospy.internal][INFO] 2017-06-10 01:55:23,368: topic[/tf] adding connection to [http://ip-172-31-19-100:57140/], count 0
[rospy.internal][INFO] 2017-06-10 01:55:23,368: topic[/joint_states] adding connection to [http://ip-172-31-19-100:37525/], count 0
[rospy.internal][INFO] 2017-06-10 01:55:23,580: topic[/joint_command] adding connection to [/robot_sim], count 0
[rospy.internal][INFO] 2017-06-10 01:55:26,363: topic[/motion_planning_goal] removing connection to /move_arm_32388_1497084268904
[rospy.internal][INFO] 2017-06-10 01:55:35,162: topic[/control_markers/update_full] removing connection to /interactive_marker_proxy
[rospy.internal][ERROR] 2017-06-10 01:56:15,442: Unable to initiate TCP/IP socket to ip-172-31-19-100:53947 (http://ip-172-31-19-100:40574/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2017-06-10 01:56:16,639: Unknown error initiating TCP/IP socket to ip-172-31-19-100:53947 (http://ip-172-31-19-100:40574/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-10 01:56:16,639: topic[/joint_trajectory] removing connection to http://ip-172-31-19-100:40574/
