[rospy.client][INFO] 2017-06-10 15:54:11,871: init_node, name[/move_arm_11456_1497135251815], pid[11456]
[xmlrpc][INFO] 2017-06-10 15:54:11,872: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-10 15:54:11,876: Started XML-RPC server [http://ip-172-31-19-100:54594/]
[rospy.init][INFO] 2017-06-10 15:54:11,876: ROS Slave URI: [http://ip-172-31-19-100:54594/]
[rospy.impl.masterslave][INFO] 2017-06-10 15:54:11,879: _ready: http://ip-172-31-19-100:54594/
[xmlrpc][INFO] 2017-06-10 15:54:11,889: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-06-10 15:54:11,890: Registering with master node http://localhost:44614
[rospy.init][INFO] 2017-06-10 15:54:11,983: registered with master
[rospy.rosout][INFO] 2017-06-10 15:54:11,987: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-10 15:54:11,999: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-10 15:54:12,004: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-10 15:54:12,275: topic[/motion_planning_goal] adding connection to [http://ip-172-31-19-100:33661/], count 0
[rospy.internal][INFO] 2017-06-10 15:54:12,277: topic[/joint_trajectory] adding connection to [/marker_control_21633_1497134230225], count 0
[rospy.internal][INFO] 2017-06-10 15:54:12,276: topic[/joint_states] adding connection to [http://ip-172-31-19-100:48447/], count 0
[rospy.internal][INFO] 2017-06-10 15:54:13,286: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-10 15:54:13,293: topic[/joint_trajectory] adding connection to [/robot_sim], count 1
[rospy.internal][INFO] 2017-06-10 15:54:13,325: topic[/attached_collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-10 15:54:13,329: topic[/collision_object] adding connection to [/move_group], count 0
[rospy.core][INFO] 2017-06-10 15:55:16,672: signal_shutdown [signal-2]
[rospy.internal][INFO] 2017-06-10 15:55:16,735: topic[/collision_object] removing connection to /move_group
[rospy.internal][INFO] 2017-06-10 15:55:16,741: topic[/joint_trajectory] removing connection to /marker_control_21633_1497134230225
[rospy.internal][INFO] 2017-06-10 15:55:16,747: topic[/joint_trajectory] removing connection to /robot_sim
[rospy.internal][INFO] 2017-06-10 15:55:16,750: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-06-10 15:55:16,755: topic[/attached_collision_object] removing connection to /move_group
[rospy.internal][INFO] 2017-06-10 15:55:16,759: topic[/motion_planning_goal] removing connection to http://ip-172-31-19-100:33661/
[rospy.internal][INFO] 2017-06-10 15:55:16,764: topic[/joint_states] removing connection to http://ip-172-31-19-100:48447/
[rospy.impl.masterslave][INFO] 2017-06-10 15:55:16,767: signal-2
[rospy.topics][WARNING] 2017-06-10 15:55:16,777: during shutdown, bad callback: <bound method MoveArm.move_arm_cb of <__main__.MoveArm object at 0x7fe16d956490>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 398, in move_arm_cb
    trajectory = self.project_plan(numpy.array(q_start), q_goal, self.q_min, self.q_max)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 383, in project_plan
    q_list = self.motion_plan(q_start, q_goal, q_min, q_max)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 331, in motion_plan
    if self.is_collision_free(closest_node.value, point):
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 295, in is_collision_free
    if not self.is_state_valid(check_point):
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 203, in is_state_valid
    res = self.state_valid_service(req)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 517, in call
    raise ServiceException("service [%s] returned no response"%self.resolved_name)
ServiceException: service [/check_state_validity] returned no response

[rospy.core][INFO] 2017-06-10 15:55:17,316: signal_shutdown [signal-2]
[rospy.core][INFO] 2017-06-10 15:55:17,320: signal_shutdown [atexit]
