[rospy.client][INFO] 2017-06-09 18:16:29,650: init_node, name[/move_arm_15635_1497057389607], pid[15635]
[xmlrpc][INFO] 2017-06-09 18:16:29,651: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-09 18:16:29,655: Started XML-RPC server [http://ip-172-31-19-100:51155/]
[rospy.init][INFO] 2017-06-09 18:16:29,655: ROS Slave URI: [http://ip-172-31-19-100:51155/]
[rospy.impl.masterslave][INFO] 2017-06-09 18:16:29,658: _ready: http://ip-172-31-19-100:51155/
[xmlrpc][INFO] 2017-06-09 18:16:29,667: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-06-09 18:16:29,667: Registering with master node http://localhost:52701
[rospy.init][INFO] 2017-06-09 18:16:29,762: registered with master
[rospy.rosout][INFO] 2017-06-09 18:16:29,766: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-09 18:16:29,775: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-09 18:16:29,780: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-09 18:16:30,011: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-09 18:16:30,013: topic[/joint_states] adding connection to [http://ip-172-31-19-100:38886/], count 0
[rospy.internal][INFO] 2017-06-09 18:16:30,014: topic[/motion_planning_goal] adding connection to [http://ip-172-31-19-100:37719/], count 0
[rospy.internal][INFO] 2017-06-09 18:16:30,016: topic[/joint_trajectory] adding connection to [/marker_control_9450_1497056458652], count 0
[rospy.internal][INFO] 2017-06-09 18:16:31,023: topic[/joint_trajectory] adding connection to [/robot_sim], count 1
[rospy.internal][INFO] 2017-06-09 18:16:31,056: topic[/collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-09 18:16:31,060: topic[/attached_collision_object] adding connection to [/move_group], count 0
[rosout][ERROR] 2017-06-09 18:16:40,442: bad callback: <bound method MoveArm.move_arm_cb of <__main__.MoveArm object at 0x7f30a2fb4410>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 331, in move_arm_cb
    trajectory = self.project_plan(numpy.array(q_start), q_goal, self.q_min, self.q_max)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 316, in project_plan
    q_list = self.motion_plan(q_start, q_goal, q_min, q_max)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 274, in motion_plan
    if self.is_collision_free(new_node.value, point):
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 246, in is_collision_free
    check_point = get_next_check_point(self, point1, point2)
NameError: global name 'get_next_check_point' is not defined

[rospy.core][INFO] 2017-06-09 18:17:07,537: signal_shutdown [signal-2]
[rospy.internal][INFO] 2017-06-09 18:17:07,566: topic[/collision_object] removing connection to /move_group
[rospy.internal][INFO] 2017-06-09 18:17:07,569: topic[/joint_trajectory] removing connection to /marker_control_9450_1497056458652
[rospy.internal][INFO] 2017-06-09 18:17:07,574: topic[/joint_trajectory] removing connection to /robot_sim
[rospy.internal][INFO] 2017-06-09 18:17:07,578: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-06-09 18:17:07,582: topic[/attached_collision_object] removing connection to /move_group
[rospy.internal][INFO] 2017-06-09 18:17:07,585: topic[/motion_planning_goal] removing connection to http://ip-172-31-19-100:37719/
[rospy.internal][WARNING] 2017-06-09 18:17:07,586: Unknown error initiating TCP/IP socket to ip-172-31-19-100:47916 (http://ip-172-31-19-100:37719/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2017-06-09 18:17:07,589: topic[/joint_states] removing connection to http://ip-172-31-19-100:38886/
[rospy.impl.masterslave][INFO] 2017-06-09 18:17:07,597: signal-2
[rospy.core][INFO] 2017-06-09 18:17:08,165: signal_shutdown [atexit]
