[rospy.client][INFO] 2017-06-09 18:30:41,029: init_node, name[/move_arm_5528_1497058240988], pid[5528]
[xmlrpc][INFO] 2017-06-09 18:30:41,030: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-09 18:30:41,034: Started XML-RPC server [http://ip-172-31-26-229:46098/]
[rospy.init][INFO] 2017-06-09 18:30:41,034: ROS Slave URI: [http://ip-172-31-26-229:46098/]
[rospy.impl.masterslave][INFO] 2017-06-09 18:30:41,037: _ready: http://ip-172-31-26-229:46098/
[xmlrpc][INFO] 2017-06-09 18:30:41,045: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-06-09 18:30:41,046: Registering with master node http://localhost:55471
[rospy.init][INFO] 2017-06-09 18:30:41,141: registered with master
[rospy.rosout][INFO] 2017-06-09 18:30:41,145: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-09 18:30:41,154: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-09 18:30:41,159: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-09 18:30:41,374: topic[/joint_states] adding connection to [http://ip-172-31-26-229:46603/], count 0
[rospy.internal][INFO] 2017-06-09 18:30:41,376: topic[/motion_planning_goal] adding connection to [http://ip-172-31-26-229:40402/], count 0
[rospy.internal][INFO] 2017-06-09 18:30:41,377: topic[/joint_trajectory] adding connection to [/marker_control_4416_1497058213851], count 0
[rospy.internal][INFO] 2017-06-09 18:30:42,229: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-09 18:30:42,233: topic[/joint_trajectory] adding connection to [/robot_sim], count 1
[rospy.internal][INFO] 2017-06-09 18:30:42,325: topic[/attached_collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-09 18:30:42,330: topic[/collision_object] adding connection to [/move_group], count 0
[rospy.core][INFO] 2017-06-09 18:31:10,825: signal_shutdown [signal-2]
[rospy.internal][INFO] 2017-06-09 18:31:10,863: topic[/collision_object] removing connection to /move_group
[rospy.internal][INFO] 2017-06-09 18:31:10,867: topic[/joint_trajectory] removing connection to /marker_control_4416_1497058213851
[rospy.internal][INFO] 2017-06-09 18:31:10,870: topic[/joint_trajectory] removing connection to /robot_sim
[rospy.internal][INFO] 2017-06-09 18:31:10,874: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-06-09 18:31:10,878: topic[/attached_collision_object] removing connection to /move_group
[rospy.internal][INFO] 2017-06-09 18:31:10,882: topic[/motion_planning_goal] removing connection to http://ip-172-31-26-229:40402/
[rospy.internal][INFO] 2017-06-09 18:31:10,887: topic[/joint_states] removing connection to http://ip-172-31-26-229:46603/
[rospy.impl.masterslave][INFO] 2017-06-09 18:31:10,890: signal-2
[rospy.topics][WARNING] 2017-06-09 18:31:10,896: during shutdown, bad callback: <bound method MoveArm.move_arm_cb of <__main__.MoveArm object at 0x7f9732737410>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 333, in move_arm_cb
    trajectory = self.project_plan(numpy.array(q_start), q_goal, self.q_min, self.q_max)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 318, in project_plan
    q_list = self.motion_plan(q_start, q_goal, q_min, q_max)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 275, in motion_plan
    if self.is_collision_free(new_node.value, point):
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 248, in is_collision_free
    if not self.is_state_valid(check_point):
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 203, in is_state_valid
    res = self.state_valid_service(req)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 517, in call
    raise ServiceException("service [%s] returned no response"%self.resolved_name)
ServiceException: service [/check_state_validity] returned no response

[rospy.core][INFO] 2017-06-09 18:31:11,459: signal_shutdown [atexit]
