[rospy.client][INFO] 2017-06-10 16:20:50,861: init_node, name[/move_arm_5476_1497136850811], pid[5476]
[xmlrpc][INFO] 2017-06-10 16:20:50,861: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-10 16:20:50,865: Started XML-RPC server [http://ip-172-31-19-100:37878/]
[rospy.impl.masterslave][INFO] 2017-06-10 16:20:50,871: _ready: http://ip-172-31-19-100:37878/
[rospy.init][INFO] 2017-06-10 16:20:50,865: ROS Slave URI: [http://ip-172-31-19-100:37878/]
[xmlrpc][INFO] 2017-06-10 16:20:50,880: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-06-10 16:20:50,880: Registering with master node http://localhost:36505
[rospy.init][INFO] 2017-06-10 16:20:50,981: registered with master
[rospy.rosout][INFO] 2017-06-10 16:20:50,985: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-10 16:20:50,996: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-10 16:20:51,001: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-10 16:20:51,286: topic[/joint_states] adding connection to [http://ip-172-31-19-100:49985/], count 0
[rospy.internal][INFO] 2017-06-10 16:20:51,286: topic[/motion_planning_goal] adding connection to [http://ip-172-31-19-100:52813/], count 0
[rospy.internal][INFO] 2017-06-10 16:20:51,290: topic[/joint_trajectory] adding connection to [/marker_control_29845_1497135347175], count 0
[rospy.internal][INFO] 2017-06-10 16:20:52,178: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-10 16:20:52,183: topic[/joint_trajectory] adding connection to [/robot_sim], count 1
[rospy.internal][INFO] 2017-06-10 16:20:52,258: topic[/collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-10 16:20:52,266: topic[/attached_collision_object] adding connection to [/move_group], count 0
[rospy.core][INFO] 2017-06-10 16:22:22,174: signal_shutdown [signal-2]
[rospy.internal][INFO] 2017-06-10 16:22:22,226: topic[/collision_object] removing connection to /move_group
[rospy.internal][INFO] 2017-06-10 16:22:22,230: topic[/joint_trajectory] removing connection to /marker_control_29845_1497135347175
[rospy.internal][INFO] 2017-06-10 16:22:22,234: topic[/joint_trajectory] removing connection to /robot_sim
[rospy.internal][INFO] 2017-06-10 16:22:22,238: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-06-10 16:22:22,242: topic[/attached_collision_object] removing connection to /move_group
[rospy.internal][INFO] 2017-06-10 16:22:22,252: topic[/motion_planning_goal] removing connection to http://ip-172-31-19-100:52813/
[rospy.internal][INFO] 2017-06-10 16:22:22,256: topic[/joint_states] removing connection to http://ip-172-31-19-100:49985/
[rospy.impl.masterslave][INFO] 2017-06-10 16:22:22,260: signal-2
[rospy.topics][WARNING] 2017-06-10 16:22:22,269: during shutdown, bad callback: <bound method MoveArm.move_arm_cb of <__main__.MoveArm object at 0x7f773fa373d0>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 403, in move_arm_cb
    trajectory = self.project_plan(numpy.array(q_start), q_goal, self.q_min, self.q_max)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 388, in project_plan
    q_list = self.motion_plan(q_start, q_goal, q_min, q_max)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 336, in motion_plan
    if self.is_collision_free(closest_node.value, point):
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 300, in is_collision_free
    if not self.is_state_valid(check_point):
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 203, in is_state_valid
    res = self.state_valid_service(req)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 517, in call
    raise ServiceException("service [%s] returned no response"%self.resolved_name)
ServiceException: service [/check_state_validity] returned no response

[rospy.core][INFO] 2017-06-10 16:22:22,830: signal_shutdown [atexit]
