[rospy.client][INFO] 2017-06-09 18:51:23,117: init_node, name[/move_arm_28290_1497059483075], pid[28290]
[xmlrpc][INFO] 2017-06-09 18:51:23,117: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-09 18:51:23,121: Started XML-RPC server [http://ip-172-31-19-100:54395/]
[rospy.init][INFO] 2017-06-09 18:51:23,121: ROS Slave URI: [http://ip-172-31-19-100:54395/]
[rospy.impl.masterslave][INFO] 2017-06-09 18:51:23,125: _ready: http://ip-172-31-19-100:54395/
[xmlrpc][INFO] 2017-06-09 18:51:23,136: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-06-09 18:51:23,136: Registering with master node http://localhost:37427
[rospy.init][INFO] 2017-06-09 18:51:23,231: registered with master
[rospy.rosout][INFO] 2017-06-09 18:51:23,235: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-09 18:51:23,244: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-09 18:51:23,249: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-09 18:51:23,485: topic[/motion_planning_goal] adding connection to [http://ip-172-31-19-100:38675/], count 0
[rospy.internal][INFO] 2017-06-09 18:51:23,489: topic[/joint_states] adding connection to [http://ip-172-31-19-100:47311/], count 0
[rospy.internal][INFO] 2017-06-09 18:51:23,492: topic[/joint_trajectory] adding connection to [/marker_control_13450_1497058913346], count 0
[rospy.internal][INFO] 2017-06-09 18:51:24,424: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-09 18:51:24,427: topic[/joint_trajectory] adding connection to [/robot_sim], count 1
[rospy.internal][INFO] 2017-06-09 18:51:24,454: topic[/collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-09 18:51:24,458: topic[/attached_collision_object] adding connection to [/move_group], count 0
[rospy.core][INFO] 2017-06-09 18:51:45,848: signal_shutdown [signal-2]
[rospy.internal][INFO] 2017-06-09 18:51:45,884: topic[/collision_object] removing connection to /move_group
[rospy.internal][INFO] 2017-06-09 18:51:45,888: topic[/joint_trajectory] removing connection to /marker_control_13450_1497058913346
[rospy.internal][INFO] 2017-06-09 18:51:45,892: topic[/joint_trajectory] removing connection to /robot_sim
[rospy.internal][INFO] 2017-06-09 18:51:45,896: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-06-09 18:51:45,900: topic[/attached_collision_object] removing connection to /move_group
[rospy.internal][INFO] 2017-06-09 18:51:45,905: topic[/motion_planning_goal] removing connection to http://ip-172-31-19-100:38675/
[rospy.internal][INFO] 2017-06-09 18:51:45,910: topic[/joint_states] removing connection to http://ip-172-31-19-100:47311/
[rospy.impl.masterslave][INFO] 2017-06-09 18:51:45,915: signal-2
[rospy.topics][WARNING] 2017-06-09 18:51:45,923: during shutdown, bad callback: <bound method MoveArm.move_arm_cb of <__main__.MoveArm object at 0x7f3adc3b6410>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 341, in move_arm_cb
    trajectory = self.project_plan(numpy.array(q_start), q_goal, self.q_min, self.q_max)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 326, in project_plan
    q_list = self.motion_plan(q_start, q_goal, q_min, q_max)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 282, in motion_plan
    if self.is_collision_free(new_node.value, point):
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 250, in is_collision_free
    print('is_collision_free: state_valid={}'.format(self.is_state_valid(check_point)))
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 203, in is_state_valid
    res = self.state_valid_service(req)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 517, in call
    raise ServiceException("service [%s] returned no response"%self.resolved_name)
ServiceException: service [/check_state_validity] returned no response

[rospy.core][INFO] 2017-06-09 18:51:46,534: signal_shutdown [atexit]
