[rospy.client][INFO] 2017-06-10 16:33:49,382: init_node, name[/move_arm_28188_1497137629332], pid[28188]
[xmlrpc][INFO] 2017-06-10 16:33:49,382: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-10 16:33:49,386: Started XML-RPC server [http://ip-172-31-19-100:45870/]
[rospy.init][INFO] 2017-06-10 16:33:49,386: ROS Slave URI: [http://ip-172-31-19-100:45870/]
[rospy.impl.masterslave][INFO] 2017-06-10 16:33:49,391: _ready: http://ip-172-31-19-100:45870/
[xmlrpc][INFO] 2017-06-10 16:33:49,401: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-06-10 16:33:49,401: Registering with master node http://localhost:51274
[rospy.init][INFO] 2017-06-10 16:33:49,494: registered with master
[rospy.rosout][INFO] 2017-06-10 16:33:49,498: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-10 16:33:49,508: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-10 16:33:49,513: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-10 16:33:49,777: topic[/joint_states] adding connection to [http://ip-172-31-19-100:48979/], count 0
[rospy.internal][INFO] 2017-06-10 16:33:49,781: topic[/motion_planning_goal] adding connection to [http://ip-172-31-19-100:52749/], count 0
[rospy.internal][INFO] 2017-06-10 16:33:49,782: topic[/joint_trajectory] adding connection to [/marker_control_18543_1497137490921], count 0
[rospy.internal][INFO] 2017-06-10 16:33:50,607: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-10 16:33:50,611: topic[/joint_trajectory] adding connection to [/robot_sim], count 1
[rospy.internal][INFO] 2017-06-10 16:33:50,644: topic[/attached_collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-10 16:33:50,650: topic[/collision_object] adding connection to [/move_group], count 0
[rospy.core][INFO] 2017-06-10 16:34:41,759: signal_shutdown [signal-2]
[rospy.internal][INFO] 2017-06-10 16:34:41,808: topic[/collision_object] removing connection to /move_group
[rospy.internal][INFO] 2017-06-10 16:34:41,812: topic[/joint_trajectory] removing connection to /marker_control_18543_1497137490921
[rospy.internal][INFO] 2017-06-10 16:34:41,816: topic[/joint_trajectory] removing connection to /robot_sim
[rospy.internal][INFO] 2017-06-10 16:34:41,829: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-06-10 16:34:41,833: topic[/attached_collision_object] removing connection to /move_group
[rospy.internal][INFO] 2017-06-10 16:34:41,836: topic[/motion_planning_goal] removing connection to http://ip-172-31-19-100:52749/
[rospy.internal][INFO] 2017-06-10 16:34:41,841: topic[/joint_states] removing connection to http://ip-172-31-19-100:48979/
[rospy.impl.masterslave][INFO] 2017-06-10 16:34:41,845: signal-2
[rospy.topics][WARNING] 2017-06-10 16:34:41,848: during shutdown, bad callback: <bound method MoveArm.move_arm_cb of <__main__.MoveArm object at 0x7f7ae674d550>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 403, in move_arm_cb
    trajectory = self.project_plan(numpy.array(q_start), q_goal, self.q_min, self.q_max)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 388, in project_plan
    q_list = self.motion_plan(q_start, q_goal, q_min, q_max)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 341, in motion_plan
    if self.is_collision_free(new_node.value, q_goal):
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 300, in is_collision_free
    if not self.is_state_valid(check_point):
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 203, in is_state_valid
    res = self.state_valid_service(req)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 517, in call
    raise ServiceException("service [%s] returned no response"%self.resolved_name)
ServiceException: service [/check_state_validity] returned no response

[rospy.core][INFO] 2017-06-10 16:34:42,415: signal_shutdown [atexit]
