[rospy.client][INFO] 2017-06-09 23:53:11,866: init_node, name[/move_arm_14276_1497077591826], pid[14276]
[xmlrpc][INFO] 2017-06-09 23:53:11,867: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-09 23:53:11,870: Started XML-RPC server [http://ip-172-31-19-100:60232/]
[rospy.init][INFO] 2017-06-09 23:53:11,871: ROS Slave URI: [http://ip-172-31-19-100:60232/]
[rospy.impl.masterslave][INFO] 2017-06-09 23:53:11,874: _ready: http://ip-172-31-19-100:60232/
[xmlrpc][INFO] 2017-06-09 23:53:11,882: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-06-09 23:53:11,882: Registering with master node http://localhost:60180
[rospy.init][INFO] 2017-06-09 23:53:11,977: registered with master
[rospy.rosout][INFO] 2017-06-09 23:53:11,981: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-09 23:53:11,990: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-09 23:53:11,994: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-09 23:53:12,205: topic[/joint_states] adding connection to [http://ip-172-31-19-100:57153/], count 0
[rospy.internal][INFO] 2017-06-09 23:53:12,206: topic[/motion_planning_goal] adding connection to [http://ip-172-31-19-100:41828/], count 0
[rospy.internal][INFO] 2017-06-09 23:53:12,213: topic[/joint_trajectory] adding connection to [/marker_control_8946_1497076857451], count 0
[rospy.internal][INFO] 2017-06-09 23:53:13,045: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-09 23:53:13,050: topic[/joint_trajectory] adding connection to [/robot_sim], count 1
[rospy.internal][INFO] 2017-06-09 23:53:13,153: topic[/collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-09 23:53:13,157: topic[/attached_collision_object] adding connection to [/move_group], count 0
[rospy.core][INFO] 2017-06-09 23:58:26,030: signal_shutdown [signal-2]
[rospy.internal][INFO] 2017-06-09 23:58:26,068: topic[/collision_object] removing connection to /move_group
[rospy.internal][INFO] 2017-06-09 23:58:26,073: topic[/joint_trajectory] removing connection to /marker_control_8946_1497076857451
[rospy.internal][INFO] 2017-06-09 23:58:26,077: topic[/joint_trajectory] removing connection to /robot_sim
[rospy.internal][INFO] 2017-06-09 23:58:26,081: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-06-09 23:58:26,084: topic[/attached_collision_object] removing connection to /move_group
[rospy.internal][INFO] 2017-06-09 23:58:26,088: topic[/motion_planning_goal] removing connection to http://ip-172-31-19-100:41828/
[rospy.internal][INFO] 2017-06-09 23:58:26,093: topic[/joint_states] removing connection to http://ip-172-31-19-100:57153/
[rospy.impl.masterslave][INFO] 2017-06-09 23:58:26,096: signal-2
[rospy.topics][WARNING] 2017-06-09 23:58:26,105: during shutdown, bad callback: <bound method MoveArm.move_arm_cb of <__main__.MoveArm object at 0x7fc98316d490>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 366, in move_arm_cb
    trajectory = self.project_plan(numpy.array(q_start), q_goal, self.q_min, self.q_max)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 351, in project_plan
    q_list = self.motion_plan(q_start, q_goal, q_min, q_max)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 298, in motion_plan
    if self.is_collision_free(closest_node.value, point):
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 260, in is_collision_free
    if not self.is_state_valid(check_point):
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 203, in is_state_valid
    res = self.state_valid_service(req)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 517, in call
    raise ServiceException("service [%s] returned no response"%self.resolved_name)
ServiceException: service [/check_state_validity] returned no response

[rospy.core][INFO] 2017-06-09 23:58:26,665: signal_shutdown [atexit]
