[rospy.client][INFO] 2017-06-10 19:43:06,768: init_node, name[/move_arm_4854_1497148986698], pid[4854]
[xmlrpc][INFO] 2017-06-10 19:43:06,771: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-10 19:43:06,776: Started XML-RPC server [http://ip-172-31-19-100:52480/]
[rospy.init][INFO] 2017-06-10 19:43:06,776: ROS Slave URI: [http://ip-172-31-19-100:52480/]
[rospy.impl.masterslave][INFO] 2017-06-10 19:43:06,779: _ready: http://ip-172-31-19-100:52480/
[rospy.registration][INFO] 2017-06-10 19:43:06,789: Registering with master node http://localhost:54283
[xmlrpc][INFO] 2017-06-10 19:43:06,789: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2017-06-10 19:43:06,883: registered with master
[rospy.rosout][INFO] 2017-06-10 19:43:06,887: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-10 19:43:06,897: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-10 19:43:06,902: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-10 19:43:07,222: topic[/motion_planning_goal] adding connection to [http://ip-172-31-19-100:47112/], count 0
[rospy.internal][INFO] 2017-06-10 19:43:07,223: topic[/joint_trajectory] adding connection to [/marker_control_4316_1497146650462], count 0
[rospy.internal][INFO] 2017-06-10 19:43:07,223: topic[/joint_states] adding connection to [http://ip-172-31-19-100:57553/], count 0
[rospy.internal][INFO] 2017-06-10 19:43:08,199: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-10 19:43:08,207: topic[/joint_trajectory] adding connection to [/robot_sim], count 1
[rospy.internal][INFO] 2017-06-10 19:43:08,216: topic[/collision_object] adding connection to [/move_group], count 0
[rospy.internal][INFO] 2017-06-10 19:43:08,222: topic[/attached_collision_object] adding connection to [/move_group], count 0
[rospy.core][INFO] 2017-06-10 19:52:46,282: signal_shutdown [signal-2]
[rospy.internal][INFO] 2017-06-10 19:52:46,318: topic[/collision_object] removing connection to /move_group
[rospy.internal][INFO] 2017-06-10 19:52:46,322: topic[/joint_trajectory] removing connection to /marker_control_4316_1497146650462
[rospy.internal][INFO] 2017-06-10 19:52:46,326: topic[/joint_trajectory] removing connection to /robot_sim
[rospy.internal][INFO] 2017-06-10 19:52:46,330: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-06-10 19:52:46,336: topic[/attached_collision_object] removing connection to /move_group
[rospy.internal][INFO] 2017-06-10 19:52:46,351: topic[/motion_planning_goal] removing connection to http://ip-172-31-19-100:47112/
[rospy.internal][INFO] 2017-06-10 19:52:46,356: topic[/joint_states] removing connection to http://ip-172-31-19-100:57553/
[rospy.impl.masterslave][INFO] 2017-06-10 19:52:46,361: signal-2
[rospy.topics][WARNING] 2017-06-10 19:52:46,373: during shutdown, bad callback: <bound method MoveArm.move_arm_cb of <__main__.MoveArm object at 0x7f014d21e390>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 421, in move_arm_cb
    print "IK solved, planning"
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 406, in project_plan
    def project_plan(self, q_start, q_goal, q_min, q_max):
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 358, in motion_plan
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 303, in is_collision_free
    #print('is_collision_free: state_valid={}'.format(self.is_state_valid(check_point)))
  File "/home/ccc_v1_w_dd4cc_18220/asn13529_Project_5/asn13530_Project_4/work/catkin_ws/src/motion_planning/scripts/motion_planning.py", line 203, in is_state_valid
    res = self.state_valid_service(req)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 517, in call
    raise ServiceException("service [%s] returned no response"%self.resolved_name)
ServiceException: service [/check_state_validity] returned no response

[rospy.core][INFO] 2017-06-10 19:52:46,965: signal_shutdown [signal-2]
[rospy.core][INFO] 2017-06-10 19:52:46,969: signal_shutdown [atexit]
